services:
  db:
    build: ./db
    container_name: moja_baza
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASS}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db-backNetwork

  migrator: 
    build: ./migrator
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db-backNetwork
    volumes:
      - prisma_shared:/usr/src/app/prisma

  back-auth:
    build:  
      context: ./back-auth
      args:
        PORT: ${VITE_AUTH_BACK_PORT}
    ports:
      - "${VITE_AUTH_BACK_PORT}:${VITE_AUTH_BACK_PORT}"
    env_file: .env
    depends_on:
      migrator:
        condition: service_started
    networks:
      - db-backNetwork
      - front-backNetwork
    volumes:
      - prisma_shared:/usr/src/app/prisma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${VITE_AUTH_BACK_PORT}/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3 
      start_period: 10s

  # back2:
  #   build: ./back-logic
  #   env_file: .env
  #   depends_on:
  #     migrator:
  #       condition: service_started
  #   networks:
  #     - db-backNetwork
  #     - front-backNetwork
  
  front:
    build: ./docker-front
    env_file: .env
    ports:
      - "80:5137"
    depends_on:
      back-auth:
        condition: service_healthy
      # back2:
      #   condition: service_healthy
    command: npm run dev -- --host
    networks:
      - front-backNetwork

volumes:
  db_data:    
  prisma_shared:

networks:
  db-backNetwork:
  front-backNetwork:    